name: Nightly

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build-release:
    uses: ./.github/workflows/build-releases.yml

  upload-release:
    runs-on: ubuntu-latest
    needs: [build-release]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./

      - name: Move artifacts
        run: |
          mkdir release
          mv release-*/* release/
          du -h -d 0 ./release/*

      - name: Delete tag and release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sleep for a few seconds to prevent timing issues between the deletion and creation of the release
        run: sleep 10

      - name: Upload all release files
        uses: softprops/action-gh-release@v0.1.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag_name: "nightly"
          draft: false
          fail_on_unmatched_files: true
          files: |
            ./release/*
